### PR TITLE
Add hotkey to cycle between hidden files

### LINKED ISSUE #10: Toggle visibility of hidden entries

### PR DESCRIPTION
**Pull request by CutestNekoAqua**
Its simple and it works.. couldn't test if windows implementation works too.
Closes #10

### CODE REVIEW

**Comment by nore-dev** [comment]
thank you for your contribution! Everything looks good but I think you accidentally add UpdateEntriesMsg instead of PathMsg. Let me know when you fix it, I will merge

**Comment by CutestNekoAqua** [comment]
Should I use PathMsg? UpdateEntriesMsg works too

**Comment by nore-dev** [comment]
@CutestNekoAqua yes

**Comment by CutestNekoAqua** [comment]
Whats the difference?

**Comment by CutestNekoAqua** [comment]
I gonna obv changd it but I am interedted 👀

**Comment by nore-dev** [comment]
list.go line 202

**Comment by nore-dev** [comment]
Sorry the code is messy i need to refactor

**Pull request merged**
